### ISSUE TITLE
Force IOMMU

### ISSUE THREAD

**Issue by TommyTran732** [Kicksecure/security-misc#175]
I noticed that IOMMU settings right now is `on` instead of `forced_isolation` on AMD. Is there a reason why we are not forcing it? I don't see the `on` option for AMD CPUs documented anywhere.

**Comment by monsieuremre** [comment]
You are right. Created #176 for this.

@adrelanos could you check the request? The current option that is set seems to be completely invalid.

**Comment by adrelanos** [comment]
Original issue resolved. Please open a new ticket should there be something else related to do such as force_enable vs force_isolation.

**Comment by TommyTran732** [comment]
@adrelanos 

Okay, I might make another issue later. Just dropping this here since it's more detailed than the kernel.org link:

https://docs.kernel.org/6.0/x86/x86_64/boot-options.html#iommu-input-output-memory-management-unit

`iommu=force` -> Force the use of the hardware IOMMU even when it is not actually needed (e.g. because < 3 GB memory).

I am not sure this actually forces IOMMU to not lift restrictions like `forced_isolation` either.

**Comment by adrelanos** [comment]
I don't think it does because it doesn't say it does.

The kernel is developed by different developers. I assume if nobody 
implemented a comparable feature for Intel or if it's not needed it's 
simply non-existing.

AMD CPUs might have a feature to disable isolation without reboot 
required. This can only be prevented by using force_isolation. Intel 
CPUs might not have the feature to disable isolation. Hence there was no 
point to implement force_isolation.

It's a different CPU. It can have different CPU features and kernel 
implementation.

If you look into other CPU architectures (ARM, ...) you might find more 
discrepancies. I don't think there is much to be surprised about here.

For the purpose of security-misc, I will simply trust the kernel manual 
if there isn't any additional information on the internet. If you want 
to dig deeper, you need to consult the kernel source code or contact the 
kernel developers. By reading the comments of the kernel source code for 
the related keywords, you might already find the answer.
