### ISSUE TITLE
default SUID for umount (un-mount) may be incorrect

### ISSUE THREAD

**Issue by the-moog** [Kicksecure/security-misc#284]
As it is required for `systemd --user` mount units, I think the default configuration for permission hardening of 
 `umount` should be in the same file as `mount` in the file `/etc/permission-hardener.d/25_default_whitelist_mount.conf`.

It's bugged me for ages why  network mounts can't restart.  Just realised why.

Also (not sure what it's supposed to be) but in the same file, I see mode 745 on mount which means group members can't execute it but anybody else can.  Surely it should be 755 or 744?   I assume this is as shipped as I've never changed it?

**Comment by adrelanos** [comment]
See https://github.com/Kicksecure/security-misc/pull/285

**Comment by ntninja** [comment]
I do not understand this issue, unmounting systemd user mounts is still broken (as I have discovered today) and the new configuration makes it harder to fix because:

```
/usr/bin/umount exactwhitelist
```

ie: What is [suggested on the Wiki](https://www.kicksecure.com/wiki/SUID_Disabler_and_Permission_Hardener#Whitelist_Specific_SUID_Binaries) does not work and does nothing.

The correct way to overrule is currently:

```
/usr/bin/umount 4755 root root
```

Unless, I missed something in the above exchange the apparent ¿fix? only moved the location of where the rule for `/usr/bin/umount` is defined, not change anything about the problem of systemd user mount unmounts being non-functional?
